/*

 @author sole / http://soledadpenades.com
 @author mr.doob / http://mrdoob.com
 @author Robert Eisele / http://www.xarg.org
 @author Philippe / http://philippe.elsass.me
 @author Robert Penner / http://www.robertpenner.com/easing_terms_of_use.html
 @author Paul Lewis / http://www.aerotwist.com/
 @author lechecacharro
 @author Josh Faul / http://jocafa.com/
*/
var TWEEN=TWEEN||function(){var e,a,b=60,c=!1,o=[],f;return{setFPS:function(a){b=a||60},start:function(c){0!==arguments.length&&this.setFPS(c);a=setInterval(this.update,1E3/b)},stop:function(){clearInterval(a)},setAutostart:function(b){(c=b)&&!a&&this.start()},add:function(b){o.push(b);c&&!a&&this.start()},getAll:function(){return o},removeAll:function(){o=[]},remove:function(a){e=o.indexOf(a);-1!==e&&o.splice(e,1)},update:function(a){e=0;f=o.length;for(a=a||(new Date).getTime();e<f;)o[e].update(a)?
e++:(o.splice(e,1),f--);0===f&&!0===c&&this.stop()}}}();
TWEEN.Tween=function(e){var a={},b={},c={},o=1E3,f=0,g=null,j=TWEEN.Easing.Linear.EaseNone,y=null,z=null,A=null;this.to=function(a,b){null!==b&&(o=b);for(var g in a)null!==e[g]&&(c[g]=a[g]);return this};this.start=function(x){TWEEN.add(this);g=x?x+f:(new Date).getTime()+f;for(var j in c)null!==e[j]&&(a[j]=e[j],b[j]=c[j]-e[j]);return this};this.stop=function(){TWEEN.remove(this);return this};this.delay=function(a){f=a;return this};this.easing=function(a){j=a;return this};this.chain=function(a){y=a;
return this};this.onUpdate=function(a){z=a;return this};this.onComplete=function(a){A=a;return this};this.update=function(c){var f,t;if(c<g)return!0;c=(c-g)/o;c=1<c?1:c;t=j(c);for(f in b)e[f]=a[f]+b[f]*t;null!==z&&z.call(e,t);return 1==c?(null!==A&&A.call(e),null!==y&&y.start(),!1):!0}};TWEEN.Easing={Linear:{},Quadratic:{},Cubic:{},Quartic:{},Quintic:{},Sinusoidal:{},Exponential:{},Circular:{},Elastic:{},Back:{},Bounce:{}};TWEEN.Easing.Linear.EaseNone=function(e){return e};
TWEEN.Easing.Cubic.EaseOut=function(e){return--e*e*e+1};/*

 @author luwes / http://luwes.co
*/
(function(e){window.requestAnimationFrame||(window.requestAnimationFrame=window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)});Flow=function(a,b,c,e,f,g,j,y,z,A,x,D,t,q,n,u,s){function v(a){for(var b=0,c=a.currentTarget;c=c.previousSibling;)++b;b=w[b];if(a.offsetY<b.halfHeight){a.preventDefault();b.index!=l?i.to(b.index):i.clicked(b.index)}}function H(a){switch(a.keyCode){case 37:i.left();
break;case 39:i.right();break;case 38:i.to(0);break;case 40:i.to(p-1);break;case 32:i.clicked(l)}}var i=this;this.GAP=f;this.ANGLE=g;this.DEPTH=-j;this.OFFSET=y+f;this.T_NEG_ANGLE="rotateY("+-this.ANGLE+"deg)";this.T_ANGLE="rotateY("+this.ANGLE+"deg)";this.OPACITY=z;this.DURATION=u;this.showComplete=this.hideComplete=null;var w=[],p=b.length,E=0,d=0,l=0,h=[],m=[];this.domElement=document.createElement("div");this.domElement.setAttribute("id","flow_wrap");this.domElement.setAttribute("class","flow_wrap");
f=document.createElement("div");f.setAttribute("id","flow_tray");f.setAttribute("class","flow_tray");this.domElement.appendChild(f);this.domElement.style.webkitPerspective=s;for(var s=new FlowDelegate(this,f),k=new TouchController(this,s,f),r=null,g=0;g<b.length;g++){r=new FlowItem(i,g,b[g].image,b[g].duration,c,e,x,D,t,A,q,n);s.cells.push(r);f.appendChild(r.domElement);r.domElement.onmousedown=v;r.domElement.style.webkitTransitionDuration=u+"s";w[g]=r}r.domElement.firstChild.addEventListener("webkitTransitionEnd",
function(a){a.stopPropagation();if(parseInt(r.domElement.firstChild.style.opacity,10)===0){i.domElement.style.opacity=0;typeof i.hideComplete=="function"&&i.hideComplete()}else parseInt(r.domElement.firstChild.style.opacity,10)===1&&typeof i.showComplete=="function"&&i.showComplete()},true);this.hide=function(a){i.hideComplete=a;for(a=0;a<w.length;a++)w[a].domElement.firstChild.style.opacity=0};this.show=function(a){i.showComplete=a;i.domElement.style.opacity=1;for(a=0;a<w.length;a++)w[a].domElement.firstChild.style.opacity=
1};this.itemComplete=function(a){d=d<a?a:d;++E;if(E==p){i.to(0);for(a=0;a<p;a++)w[a].setY(d)}};this.left=function(){l>0&&i.to(l-1)};this.right=function(){l<p-1&&i.to(l+1)};this.prev=function(){l>0?i.to(l-1):i.to(p-1)};this.next=function(){l<p-1?i.to(l+1):i.to(0)};this.to=function(a){a>p-1?a=p-1:a<0&&(a=0);l=a;k.to(a)};this.focused=function(a){for(var b=0;b<h.length;b++)h[b](a)};this.clicked=function(a){for(var b=0;b<m.length;b++)m[b](a)};this.onFocus=function(a){h.push(a)};this.onClick=function(a){m.push(a)};
this.destroy=function(){a.removeChild(i.domElement);a.removeEventListener("touchstart",k,true);window.removeEventListener("keydown",H,false)};a.addEventListener("touchstart",k,true);window.addEventListener("keydown",H,false)};FlowItem=function(a,b,c,e,f,g,j,y,z,A,x,D){var t=this,q,n;this.index=b;this.halfHeight=0;this.domElement=document.createElement("div");this.domElement.className="flow_cell";var u=this.domElement.style;u.backgroundColor=A;var s=document.createElement("canvas");t.domElement.appendChild(s);
var v=document.createElement("img");v.addEventListener("load",function(){var b=v.width,c=v.height,e=0,p=0,o=0;if(x){var d=document.createElement("canvas");d.width=b;d.height=c;d=d.getContext("2d");d.drawImage(v,0,0);for(var d=d.getImageData(0,0,b,c).data,l=0,h=0,m=0,k=0;k<c;k++){for(h=l=0;h<b;h++){m=(k*b+h)*4;l=l+(d[m]<<16|d[m+1]<<8|d[m+2])}if(l/b<460551)e++;else break}for(k=c-1;k>=0;k--){for(h=l=0;h<b;h++){m=(k*b+h)*4;l=l+(d[m]<<16|d[m+1]<<8|d[m+2])}if(l/b<460551)p++;else break}c=c-(e+p)}if(D){q=
Math.round(f);n=Math.round(g);if(q/b<n/c){p=n/c;o=o+(b-q/p)*0.5}else{p=q/b;e=e+(c-n/p)*0.5}}else if(f>=g){q=Math.round(b/c*g);n=Math.round(g)}else{q=Math.round(f);n=Math.round(c/b*f)}t.halfHeight=n;u.top=-(n*0.5)+"px";u.left=-(q*0.5)+"px";u.width=q+"px";u.height=n+"px";s.width=q;s.height=n*2;s.getContext("2d").drawImage(v,o,e,b-2*o,c-2*e,0,0,q,n);if(j>0){u.height=n*2+"px";t.reflect(s,q,n,j,y,z)}a.itemComplete(n)});v.src=c;this.setY=function(a){this.domElement.style.top=-(a*0.5-(a-n))+"px"}};FlowItem.prototype.reflect=
function(a,b,c,e,f,g){var j=a.getContext("2d");j.save();j.scale(1,-1);j.drawImage(a,0,-c*2-g);j.restore();j.globalCompositeOperation="destination-out";a=j.createLinearGradient(0,0,0,c);a.addColorStop(f/255,"rgba(255, 255, 255, 1.0)");a.addColorStop(0,"rgba(255, 255, 255, "+(1-e)+")");j.translate(0,c+g);j.fillStyle=a;j.fillRect(0,0,b,c)};TouchController=function(a,b,c){this.flow=a;this.delegate=b;this.elem=c;this.currentX=0};TouchController.prototype.touchstart=function(a){a.stopImmediatePropagation();
this.startX=a.touches[0].pageX-this.currentX;this.pageY=a.touches[0].pageY;this.touchMoved=false;window.addEventListener("touchmove",this,true);window.addEventListener("touchend",this,true);this.elem.style.webkitTransitionDuration="0s"};TouchController.prototype.touchmove=function(a){a.stopImmediatePropagation();this.touchMoved=true;this.lastX=this.currentX;this.lastMoveTime=(new Date).getTime();this.currentX=a.touches[0].pageX-this.startX;this.delegate.update(this.currentX)};TouchController.prototype.touchend=
function(a){a.stopImmediatePropagation();window.removeEventListener("touchmove",this,true);window.removeEventListener("touchend",this,true);this.elem.style.webkitTransitionDuration=this.flow.DURATION+"s";if(this.touchMoved){var a=this.currentX-this.lastX,b=(new Date).getTime()-this.lastMoveTime+1;this.currentX=this.currentX+a*50/b;this.delegate.updateTouchEnd(this)}else this.delegate.click(a,this.pageY,this.currentX)};TouchController.prototype.to=function(a){this.currentX=-a*this.delegate.flow.GAP;
this.delegate.update(this.currentX)};TouchController.prototype.handleEvent=function(a){this[a.type](a);a.preventDefault()};FlowDelegate=function(a,b){this.flow=a;this.elem=b;this.cells=[];this.transforms=[];this.prevF=-1};FlowDelegate.prototype.updateTouchEnd=function(a){var b=this.getFocusedCell(a.currentX);a.currentX=-b*this.flow.GAP;this.update(a.currentX)};FlowDelegate.prototype.getFocusedCell=function(a){a=-Math.round(a/this.flow.GAP);return Math.min(Math.max(a,0),this.cells.length-1)};FlowDelegate.prototype.getFocusedCellOne=
function(a){a=-Math.round(a/this.flow.GAP);return Math.min(Math.max(a,-1),this.cells.length)};FlowDelegate.prototype.click=function(a,b,c){c=-Math.round(c/this.flow.GAP);c=this.cells[c];if(c.domElement==a.target.parentNode){a=this.findPos(c.domElement);b-a.y<c.halfHeight&&this.flow.clicked(c.index)}};FlowDelegate.prototype.findPos=function(a){var b=0,c=0;if(a.offsetParent){do{b=b+a.offsetLeft;c=c+a.offsetTop}while(a=a.offsetParent);return{x:b,y:c}}};FlowDelegate.prototype.setStyleForCell=function(a,
b,c){if(this.transforms[b]!=c){a.domElement.style.webkitTransform=c;this.transforms[b]=c}};FlowDelegate.prototype.transformForCell=function(a,b){var c=b*this.flow.GAP;return a==b?"translate3d("+c+"px, 0, 0)":b>a?"translate3d("+(c+this.flow.OFFSET)+"px, 0, "+this.flow.DEPTH+"px) "+this.flow.T_NEG_ANGLE:"translate3d("+(c-this.flow.OFFSET)+"px, 0, "+this.flow.DEPTH+"px) "+this.flow.T_ANGLE};FlowDelegate.prototype.update=function(a){this.elem.style.webkitTransform="translate3d("+a+"px, 0, 0)";var b=this.getFocusedCellOne(a);
if(b!=this.prevF){this.flow.focused(b);for(var c=0;c<this.cells.length;c++)this.cells[c].domElement.style.zIndex=c<b?c:this.cells.length-c+b-1;this.prevF=b}for(c=0;c<this.cells.length;c++)this.setStyleForCell(this.cells[c],c,this.transformForCell(b,c,a))};e().registerPlugin("flow-2",function(a,b,c){function o(a){a.preventDefault();var b=Math.ceil(Math.abs(a.wheelDelta)/120);if(b>0){var c=Math.abs(a.wheelDelta)/a.wheelDelta,a=null;if(c>0)a=d.left;else if(c<0)a=d.right;if(typeof a==="function")for(c=
0;c<b;c++)a()}}function f(){if(!l[a.getCurrentItem()]["ova.hidden"]){a.pause(true);d.show()}}function g(){return a.getContainer().getElementsByTagName("video")[0]}function j(){return b.position=="left"||b.position=="right"||b.position=="top"||b.position=="bottom"}function y(a){if(b.showtext===true){var c=k[a];if(c)m.innerHTML="<h1>"+(c.title===void 0?"":c.title)+"</h1><h2>"+(c.description===void 0?"":c.description)+"</h2>"}for(c=0;c<I.length;c++)I[c](a)}function z(c){b.rotatedelay>0&&G&&d.stopRotation();
if(b.file===void 0)r[c]!=a.getCurrentItem()?a.playlistItem(r[c]):a.getState()=="PLAYING"?a.pause(true):a.play(true);else{k[c].link&&window.open(k[c].link,a.config.linktarget);if(k[c].file){a.load({file:k[c].file,image:k[c].image});a.play()}}for(var e=0;e<J.length;e++)J[e](c)}function A(a){if(a.target==c)if(parseInt(c.style.opacity,10)===0)t();else{if(b.showtext===true)m.style.opacity=1;h.show(q)}}function x(){F=false;a.resize()}function D(){c.style.opacity=0}function t(){w(false);B=false}function q(){B=
false;if(!j()&&g()){var a=g().style.webkitTransform;a?g().style.webkitTransform=a.replace(/translate\(.+?\)/,"translate(-"+d.width+"px,-"+d.height+"px)"):g().style.webkitTransform="translate(-"+d.width+"px,-"+d.height+"px)"}}function n(C){l=C.playlist;b.coverheight=b.coverheight=="auto"?a.config.height:b.coverheight;if(b.file===void 0){k=[];r=[];for(var d=C=0;d<l.length;d++){var f=l[d];if(!f["ova.hidden"]&&f.image){k[C]={title:f.title,description:f.description};k[C].image=f.image;if(b.showduration)k[C].duration=
f.duration;r[C]=d;C++}}h&&h.destroy();h=new Flow(c,k,b.coverwidth,b.coverheight,b.covergap,b.coverangle,b.coverdepth,b.coveroffset,b.opacitydecrease,b.backgroundcolor,b.reflectionopacity,b.reflectionratio,b.reflectionoffset,b.removeblackborder,b.fixedsize,b.tweentime,b.focallength);c.appendChild(h.domElement);s()}else e.utils.ajax(b.file,u)}function u(a){try{var d=e.utils.parsers.rssparser.parse(a.responseXML.firstChild);if(d.length>0){k=[];for(a=0;a<d.length;a++){var f=d[a];k[a]={title:f.title,description:f.description,
link:f.link,file:f.file};k[a].image=f.image;if(b.showduration)k[a].duration=f.duration}h&&h.destroy();h=new Flow(c,k,b.coverwidth,b.coverheight,b.covergap,b.coverangle,b.coverdepth,b.coveroffset,b.opacitydecrease,b.backgroundcolor,b.reflectionopacity,b.reflectionratio,b.reflectionoffset,b.removeblackborder,b.fixedsize,b.tweentime,b.focallength);c.appendChild(h.domElement);s();h.to(0)}}catch(g){}}function s(){h.onFocus(y);h.onClick(z);m&&c.removeChild(m);if(b.showtext===true){m=document.createElement("div");
m.setAttribute("id","flow_textfield");c.appendChild(m)}d.resize();v();c.style.display="block";if(b.onidle=="hide"){c.style.display="none";w(false);c.style.opacity=0;h.hide(null);m.style.opacity=0}if(b.rotatedelay>0){G&&d.stopRotation();G=setInterval(p,b.rotatedelay);c.addEventListener("touchstart",d.stopRotation,false);c.addEventListener("mousedown",d.stopRotation,false)}B=false;if(b.file!==void 0&&(a.getState()=="PLAYING"||a.getState()=="BUFFERING"))b.onplaying=="show"?d.show():b.onplaying=="hide"&&
d.hide()}function v(){l[a.getCurrentItem()]["ova.hidden"]?d.hide():b.file===void 0&&h.to(r.indexOf(a.getCurrentItem()))}function H(){b.oncompleted=="show"?d.show():b.oncompleted=="hide"&&d.hide()}function i(){document.getElementById(a.id+"_displayarea").style.display="block";switch(a.getState()){case "PAUSED":b.onpaused=="show"?d.show():b.onpaused=="hide"&&d.hide();break;case "BUFFERING":case "PLAYING":b.onplaying=="show"?d.show():b.onplaying=="hide"&&d.hide()}}function w(a){c.style.display=a?"block":
"none"}function p(){h.next()}function E(){window.requestAnimationFrame(E);TWEEN.update()}var d=this,l,h,m,k,r,B=false,G,M=this.height=this.width=0,F=false,I=[],J=[],K=[],L=[],N={size:150,backgroundcolor:"000000",gradientcolor:void 0,coverwidth:150,coverheight:"auto",covergap:40,coverangle:70,coverdepth:170,coveroffset:130,removeblackborder:false,fixedsize:false,focallength:250,opacitydecrease:0.1,reflectionopacity:0.3,reflectionratio:155,reflectionoffset:0,showduration:true,showtext:true,textstyle:"div#flow_textfield{color:#f1f1f1; text-align:center; font-family:Arial Rounded MT Bold;} #flow_textfield h1{font-size:14px; font-weight:normal; line-height:21px;} #flow_textfield h2{font-size:11px; font-weight:normal;}",
textoffset:75,tweentime:0.8,rotatedelay:0,dockicon:true,onidle:"show",onpaused:"hide",onplaying:"hide",oncompleted:"show",file:void 0,xposition:0,yposition:0};a.onReady(function(){if(a.getRenderingMode()=="html5"){for(var d in N)b[d]===void 0&&(b[d]=N[d]);d=document.getElementsByTagName("head")[0];var e=document.createElement("style"),h=b.textstyle;e.setAttribute("type","text/css");e.appendChild(document.createTextNode(".jwplayer_flow {overflow:hidden;-webkit-touch-callout:none;-webkit-text-size-adjust:none;-webkit-tap-highlight-color:rgba(0,0,0,0);opacity:1;-webkit-transition:opacity .7s;}.jwplayer_flow div.flow_wrap {position:absolute;left:50%;top:50%;-webkit-perspective:250;-webkit-transform-style:preserve-3d;}.jwplayer_flow div.flow_tray {-webkit-transform-style:preserve-3d;}.jwplayer_flow div.flow_tray,.jwplayer_flow div.flow_cell {position:absolute;-webkit-transform:translate3d(0,0,0);-webkit-backface-visibility:hidden;-webkit-transition:-webkit-transform .8s cubic-bezier(0.190,1.000,0.220,1.000);}.jwplayer_flow div.flow_cell canvas {position:absolute;opacity:1;-webkit-transition:opacity .7s;}#flow_textfield {position:absolute;width:100%;opacity:1;-webkit-transition:opacity .7s;}#flow_textfield h1,#flow_textfield h2{margin:0;}"));
e.appendChild(document.createTextNode(h));d.appendChild(e);c.className=c.className+"jwplayer_flow";c.addEventListener("webkitTransitionEnd",A);M=b.size;b.backgroundcolor=b.backgroundcolor.indexOf("#")==-1?"#"+b.backgroundcolor:b.backgroundcolor;c.style.backgroundColor=b.backgroundcolor;if(b.gradientcolor!==void 0){b.gradientcolor=b.gradientcolor.indexOf("#")==-1?"#"+b.gradientcolor:b.gradientcolor;c.style.background="-webkit-gradient(linear, left top, left bottom, from("+b.gradientcolor+"), to("+
b.backgroundcolor+"))"}b.dockicon===true&&a.getPlugin("dock")&&a.getPlugin("dock").setButton("flow",f,"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAABx0RVh0U29mdHdhcmUAQWRvYmUgRmlyZXdvcmtzIENTNXG14zYAAAAVdEVYdENyZWF0aW9uIFRpbWUANi8xOC8xMex3F/gAAAGLSURBVGiB7ZjxUYMwFIe/5/m/jOAI3UDcACfQDawbdARGYIOygbgBI7Qb4AS//kF6h4hykKIR89310hLyeN+9JORqklgDV7+dwKWIIqERRUIjioRGFAmNfy+y5LlmVuzVVOTac7wAw79C5xg2N8BqKhJFQiOKhEYUCY0oEhpRJDRWI+J7aLRee4lYsxgVMfscX9Lg9UvwVeyxv3ZnTS1bysIj9mrWSBQJjckiklINk3b60gVy/Raf7fcFqDu/a2Djl858fKZWbWZV59P0b5CUSTq4KlWSNu56IWnrvqeuL+n3/ZRI7hKoJOUDErfAHqiAeyABStfdAOdkM+AOSN2YR+AwNRmfqVV3Hjj04CfXbs2skbQD9m79FMCzSzwD3lybAO9mVvaDjeEjUphZNWegmdWSjrRVSVxb8rFqk1hy+y1cm7sq7IBjR76krVppZudNIyU0ETM7AA+0yb3Srousc0sO3NCuIVzbzJlWADZ2GFvwWDWJRQ6NIRJFQiOKhEYUCY3R98hfYTUVOQH3ZLQrcMqAigAAAABJRU5ErkJggg==",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAABx0RVh0U29mdHdhcmUAQWRvYmUgRmlyZXdvcmtzIENTNXG14zYAAAAVdEVYdENyZWF0aW9uIFRpbWUANi8xOC8xMex3F/gAAAGLSURBVGiB7ZjxUYMwFIe/5/m/jOAI3UDcACfQDawbdARGYIOygbgBI7Qb4AS//kF6h4hykKIR89310hLyeN+9JORqklgDV7+dwKWIIqERRUIjioRGFAmNfy+y5LlmVuzVVOTac7wAw79C5xg2N8BqKhJFQiOKhEYUCY0oEhpRJDRWI+J7aLRee4lYsxgVMfscX9Lg9UvwVeyxv3ZnTS1bysIj9mrWSBQJjckiklINk3b60gVy/Raf7fcFqDu/a2Djl858fKZWbWZV59P0b5CUSTq4KlWSNu56IWnrvqeuL+n3/ZRI7hKoJOUDErfAHqiAeyABStfdAOdkM+AOSN2YR+AwNRmfqVV3Hjj04CfXbs2skbQD9m79FMCzSzwD3lybAO9mVvaDjeEjUphZNWegmdWSjrRVSVxb8rFqk1hy+y1cm7sq7IBjR76krVppZudNIyU0ETM7AA+0yb3Srousc0sO3NCuIVzbzJlWADZ2GFvwWDWJRQ6NIRJFQiOKhEYUCY3R98hfYTUVOQH3ZLQrcMqAigAAAABJRU5ErkJggg==");
a.onPlaylist(n);a.onPlaylistItem(v);a.onPlay(i);a.onBuffer(i);a.onPause(i);a.onComplete(H);c.addEventListener("mousewheel",o)}});this.stopRotation=function(){c.removeEventListener("touchstart",d.stopRotation,false);c.removeEventListener("mousedown",d.stopRotation,false);clearInterval(G)};this.left=function(){a.getRenderingMode()=="html5"?h.left():a.getRenderingMode()=="flash"&&a.getContainer().flowLeft()};this.right=function(){a.getRenderingMode()=="html5"?h.right():a.getRenderingMode()=="flash"&&
a.getContainer().flowRight()};this.prev=function(){a.getRenderingMode()=="html5"?h.prev():a.getRenderingMode()=="flash"&&a.getContainer().flowPrev()};this.next=function(){a.getRenderingMode()=="html5"?h.next():a.getRenderingMode()=="flash"&&a.getContainer().flowNext()};this.to=function(b){a.getRenderingMode()=="html5"?h.to(b):a.getRenderingMode()=="flash"&&a.getContainer().flowTo(b)};this.onFocus=function(b){a.getRenderingMode()=="html5"?I.push(b):a.getRenderingMode()=="flash"&&a.getContainer().flowOnFocus(b.toString())};
this.onClick=function(b){a.getRenderingMode()=="html5"?J.push(b):a.getRenderingMode()=="flash"&&a.getContainer().flowOnClick(b.toString())};this.hide=function(){if(a.getRenderingMode()=="html5"){if(!(B||c.style.display!="none"===false)){B=true;if(j())(new TWEEN.Tween(b)).to({size:0},400).easing(TWEEN.Easing.Cubic.EaseOut).onUpdate(x).onComplete(t).start();else{setTimeout(function(){if(b.showtext===true)m.style.opacity=0;h.hide(D)},100);if(g()){var d=g().style.webkitTransform;g().style.webkitTransform=
d.replace(/translate\(.+?\)/,"translate(0px,0px)")}}for(d=0;d<L.length;d++)L[d]()}}else a.getRenderingMode()=="flash"&&a.getContainer().flowHide()};this.show=function(){if(a.getRenderingMode()=="html5"){if(!(B||c.style.display!="none"===true)){B=true;w(true);if(j()){b.size=1;x();(new TWEEN.Tween(b)).to({size:M},400).easing(TWEEN.Easing.Cubic.EaseOut).onUpdate(x).onComplete(q).start()}else setTimeout(function(){c.style.opacity=1},100);for(var d=0;d<K.length;d++)K[d]()}}else a.getRenderingMode()=="flash"&&
a.getContainer().flowShow()};this.onHide=function(b){a.getRenderingMode()=="html5"?L.push(b):a.getRenderingMode()=="flash"&&a.getContainer().flowOnHide(b.toString())};this.onShow=function(b){a.getRenderingMode()=="html5"?K.push(b):a.getRenderingMode()=="flash"&&a.getContainer().flowOnShow(b.toString())};this.getDisplayElement=function(){return c};this.resize=function(e,f){if(a.getRenderingMode()=="html5"){if(e)d.width=e;if(f)d.height=f;var g=d.width,i=d.height;if(j()&&b.size>0){if(b.position=="left"||
b.position=="right"){g=b.size;i=a.config.height;if(!F){F=true;a.resize(a.config.width-g,a.config.height)}c.style[b.position]=-b.size+"px"}else if(b.position=="top"||b.position=="bottom"){g=a.config.width;i=b.size;if(!F){F=true;a.resize(a.config.width,a.config.height-i)}if(b.position=="top")c.style.top=-i+"px";else if(b.position=="bottom")c.style.top=a.config.height-i+"px"}a.getContainer().style["margin"+(b.position.substr(0,1).toUpperCase()+b.position.substr(1))]=b.size+"px"}c.style.width=g+"px";
c.style.height=i+"px";if(h){h.domElement.style.left=g*0.5+b.xposition+"px";h.domElement.style.top=i*0.5+b.yposition+"px"}if(m)m.style.top=i-b.textoffset+"px"}else c.parentNode&&c.parentNode.removeChild(c)};E()},"./flow-2.swf")})(jwplayer);
