/*

 @author sole / http://soledadpenades.com
 @author mr.doob / http://mrdoob.com
 @author Robert Eisele / http://www.xarg.org
 @author Philippe / http://philippe.elsass.me
 @author Robert Penner / http://www.robertpenner.com/easing_terms_of_use.html
 @author Paul Lewis / http://www.aerotwist.com/
 @author lechecacharro
 @author Josh Faul / http://jocafa.com/
*/
var TWEEN=TWEEN||function(){var a,b,c=60,p=!1,f=[],e;return{setFPS:function(a){c=a||60},start:function(a){0!==arguments.length&&this.setFPS(a);b=setInterval(this.update,1E3/c)},stop:function(){clearInterval(b)},setAutostart:function(a){(p=a)&&!b&&this.start()},add:function(a){f.push(a);p&&!b&&this.start()},getAll:function(){return f},removeAll:function(){f=[]},remove:function(b){a=f.indexOf(b);-1!==a&&f.splice(a,1)},update:function(b){a=0;e=f.length;for(b=b||(new Date).getTime();a<e;)f[a].update(b)?
a++:(f.splice(a,1),e--);0===e&&!0===p&&this.stop()}}}();
TWEEN.Tween=function(a){var b={},c={},p={},f=1E3,e=0,m=null,A=TWEEN.Easing.Linear.EaseNone,y=null,z=null,v=null;this.to=function(b,c){null!==c&&(f=c);for(var e in b)null!==a[e]&&(p[e]=b[e]);return this};this.start=function(f){TWEEN.add(this);m=f?f+e:(new Date).getTime()+e;for(var n in p)null!==a[n]&&(b[n]=a[n],c[n]=p[n]-a[n]);return this};this.stop=function(){TWEEN.remove(this);return this};this.delay=function(a){e=a;return this};this.easing=function(a){A=a;return this};this.chain=function(a){y=a;
return this};this.onUpdate=function(a){z=a;return this};this.onComplete=function(a){v=a;return this};this.update=function(e){var n,o;if(e<m)return!0;e=(e-m)/f;e=1<e?1:e;o=A(e);for(n in c)a[n]=b[n]+c[n]*o;null!==z&&z.call(a,o);return 1==e?(null!==v&&v.call(a),null!==y&&y.start(),!1):!0}};TWEEN.Easing={Linear:{},Quadratic:{},Cubic:{},Quartic:{},Quintic:{},Sinusoidal:{},Exponential:{},Circular:{},Elastic:{},Back:{},Bounce:{}};TWEEN.Easing.Linear.EaseNone=function(a){return a};
TWEEN.Easing.Cubic.EaseOut=function(a){return--a*a*a+1};/*

 @author luwes / http://luwes.co
*/
window.requestAnimationFrame||(window.requestAnimationFrame=function(){return window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)}}());
var main=function(a,b,c){function p(a){a.preventDefault();var b=Math.ceil(Math.abs(a.wheelDelta)/120);if(b>0){var c=Math.abs(a.wheelDelta)/a.wheelDelta,a=null;if(c>0)a=d.left;else if(c<0)a=d.right;if(typeof a==="function")for(c=0;c<b;c++)a()}}function f(){if(!k[a.getCurrentItem()]["ova.hidden"]){a.pause(true);d.show()}}function e(){return a.getContainer().getElementsByTagName("video")[0]}function m(){return b.position=="left"||b.position=="right"||b.position=="top"||b.position=="bottom"}function A(a){if(b.showtext===
true){var c=j[a];if(c)l.innerHTML="<h1>"+(c.title===void 0?"":c.title)+"</h1><h2>"+(c.description===void 0?"":c.description)+"</h2>"}for(c=0;c<G.length;c++)G[c](a)}function y(c){b.rotatedelay>0&&E&&d.stopRotation();if(b.file===void 0)t[c]!=a.getCurrentItem()?a.playlistItem(t[c]):a.getState()=="PLAYING"?a.pause(true):a.play(true);else{j[c].link&&window.open(j[c].link,a.config.linktarget);if(j[c].file){a.load({file:j[c].file,image:j[c].image});a.play()}}for(var i=0;i<H.length;i++)H[i](c)}function z(a){if(a.target==
c)if(parseInt(c.style.opacity,10)===0)n();else{if(b.showtext===true)l.style.opacity=1;g.show(o)}}function v(){C=false;a.resize()}function B(){c.style.opacity=0}function n(){r(false);i=false}function o(){i=false;if(!m()&&e()){var a=e().style.webkitTransform;a?e().style.webkitTransform=a.replace(/translate\(.+?\)/,"translate(-"+d.width+"px,-"+d.height+"px)"):e().style.webkitTransform="translate(-"+d.width+"px,-"+d.height+"px)"}}function q(i){k=i.playlist;b.coverheight=b.coverheight=="auto"?a.config.height:
b.coverheight;if(b.file===void 0){j=[];t=[];for(var e=i=0;e<k.length;e++){var d=k[e];if(!d["ova.hidden"]&&d.image){j[i]={title:d.title,description:d.description};j[i].image=d.image;if(b.showduration)j[i].duration=d.duration;t[i]=e;i++}}g&&g.destroy();g=new Flow(c,j,b.coverwidth,b.coverheight,b.covergap,b.coverangle,b.coverdepth,b.coveroffset,b.opacitydecrease,b.backgroundcolor,b.reflectionopacity,b.reflectionratio,b.reflectionoffset,b.removeblackborder,b.fixedsize,b.tweentime,b.focallength);c.appendChild(g.domElement);
u()}else jwplayer.utils.ajax(b.file,w)}function w(a){try{var i=jwplayer.utils.parsers.rssparser.parse(a.responseXML.firstChild);if(i.length>0){j=[];for(a=0;a<i.length;a++){var d=i[a];j[a]={title:d.title,description:d.description,link:d.link,file:d.file};j[a].image=d.image;if(b.showduration)j[a].duration=d.duration}g&&g.destroy();g=new Flow(c,j,b.coverwidth,b.coverheight,b.covergap,b.coverangle,b.coverdepth,b.coveroffset,b.opacitydecrease,b.backgroundcolor,b.reflectionopacity,b.reflectionratio,b.reflectionoffset,
b.removeblackborder,b.fixedsize,b.tweentime,b.focallength);c.appendChild(g.domElement);u();g.to(0)}}catch(e){}}function u(){g.onFocus(A);g.onClick(y);l&&c.removeChild(l);if(b.showtext===true){l=document.createElement("div");l.setAttribute("id","flow_textfield");c.appendChild(l)}d.resize();x();c.style.display="block";if(b.onidle=="hide"){c.style.display="none";r(false);c.style.opacity=0;g.hide(null);l.style.opacity=0}if(b.rotatedelay>0){E&&d.stopRotation();E=setInterval(s,b.rotatedelay);c.addEventListener("touchstart",
d.stopRotation,false);c.addEventListener("mousedown",d.stopRotation,false)}i=false;if(b.file!==void 0&&(a.getState()=="PLAYING"||a.getState()=="BUFFERING"))b.onplaying=="show"?d.show():b.onplaying=="hide"&&d.hide()}function x(){k[a.getCurrentItem()]["ova.hidden"]?d.hide():b.file===void 0&&g.to(t.indexOf(a.getCurrentItem()))}function F(){b.oncompleted=="show"?d.show():b.oncompleted=="hide"&&d.hide()}function h(){switch(a.getState()){case "PAUSED":b.onpaused=="show"?d.show():b.onpaused=="hide"&&d.hide();
break;case "BUFFERING":case "PLAYING":b.onplaying=="show"?d.show():b.onplaying=="hide"&&d.hide()}}function r(a){c.style.display=a?"block":"none"}function s(){g.next()}function D(){window.requestAnimationFrame(D);TWEEN.update()}var d=this,k,g,l,j,t,i=false,E,K=this.height=this.width=0,C=false,G=[],H=[],I=[],J=[],L={size:150,backgroundcolor:"000000",gradientcolor:void 0,coverwidth:150,coverheight:"auto",covergap:40,coverangle:70,coverdepth:170,coveroffset:130,removeblackborder:false,fixedsize:false,
focallength:250,opacitydecrease:0.1,reflectionopacity:0.3,reflectionratio:155,reflectionoffset:0,showduration:true,showtext:true,textstyle:"div#flow_textfield{color:#f1f1f1; text-align:center; font-family:Arial Rounded MT Bold;} #flow_textfield h1{font-size:14px; font-weight:normal; line-height:21px;} #flow_textfield h2{font-size:11px; font-weight:normal;}",textoffset:75,tweentime:0.8,rotatedelay:0,dockicon:true,onidle:"show",onpaused:"hide",onplaying:"hide",oncompleted:"show",file:void 0,xposition:0,
yposition:0};a.onReady(function(){if(a.getRenderingMode()=="html5"){for(var i in L)b[i]===void 0&&(b[i]=L[i]);i=document.getElementsByTagName("head")[0];var d=document.createElement("style"),e=b.textstyle;d.setAttribute("type","text/css");d.appendChild(document.createTextNode(".jwplayer_flow {overflow:hidden;-webkit-touch-callout:none;-webkit-text-size-adjust:none;-webkit-tap-highlight-color:rgba(0,0,0,0);opacity:1;-webkit-transition:opacity .7s;}.jwplayer_flow div.flow_wrap {position:absolute;left:50%;top:50%;-webkit-perspective:250;-webkit-transform-style:preserve-3d;}.jwplayer_flow div.flow_tray {-webkit-transform-style:preserve-3d;}.jwplayer_flow div.flow_tray,.jwplayer_flow div.flow_cell {position:absolute;-webkit-transform:translate3d(0,0,0);-webkit-backface-visibility:hidden;-webkit-transition:-webkit-transform .8s cubic-bezier(0.190,1.000,0.220,1.000);}.jwplayer_flow div.flow_cell canvas {position:absolute;opacity:1;-webkit-transition:opacity .7s;}#flow_textfield {position:absolute;width:100%;opacity:1;-webkit-transition:opacity .7s;}#flow_textfield h1,#flow_textfield h2{margin:0;}"));
d.appendChild(document.createTextNode(e));i.appendChild(d);c.className=c.className+"jwplayer_flow";c.addEventListener("webkitTransitionEnd",z);K=b.size;b.backgroundcolor=b.backgroundcolor.indexOf("#")==-1?"#"+b.backgroundcolor:b.backgroundcolor;c.style.backgroundColor=b.backgroundcolor;if(b.gradientcolor!==void 0){b.gradientcolor=b.gradientcolor.indexOf("#")==-1?"#"+b.gradientcolor:b.gradientcolor;c.style.background="-webkit-gradient(linear, left top, left bottom, from("+b.gradientcolor+"), to("+
b.backgroundcolor+"))"}b.dockicon===true&&typeof a.addButton==="function"&&a.addButton("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABYAAAAPCAYAAADgbT9oAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAABV0RVh0Q3JlYXRpb24gVGltZQA2LzE4LzEx7HcX+AAAABx0RVh0U29mdHdhcmUAQWRvYmUgRmlyZXdvcmtzIENTNui8sowAAABCSURBVDiN7ZMxDgAgCAMP4/+/XAcjIQ4OBDduYeq1CyZJgFGLRrHQmbGFvVxJ18kawLfFLW5xix/El7brZvDst8ULHQsIIS+DTYcAAAAASUVORK5CYII=","Show Playlist",f,"flow");a.onPlaylist(q);a.onPlaylistItem(x);a.onPlay(h);a.onBuffer(h);
a.onPause(h);a.onComplete(F);c.addEventListener("mousewheel",p)}});this.stopRotation=function(){c.removeEventListener("touchstart",d.stopRotation,false);c.removeEventListener("mousedown",d.stopRotation,false);clearInterval(E)};this.left=function(){a.getRenderingMode()=="html5"?g.left():a.getRenderingMode()=="flash"&&a.getContainer().flowLeft()};this.right=function(){a.getRenderingMode()=="html5"?g.right():a.getRenderingMode()=="flash"&&a.getContainer().flowRight()};this.prev=function(){a.getRenderingMode()==
"html5"?g.prev():a.getRenderingMode()=="flash"&&a.getContainer().flowPrev()};this.next=function(){a.getRenderingMode()=="html5"?g.next():a.getRenderingMode()=="flash"&&a.getContainer().flowNext()};this.to=function(b){a.getRenderingMode()=="html5"?g.to(b):a.getRenderingMode()=="flash"&&a.getContainer().flowTo(b)};this.onFocus=function(b){a.getRenderingMode()=="html5"?G.push(b):a.getRenderingMode()=="flash"&&a.getContainer().flowOnFocus(b.toString())};this.onClick=function(b){a.getRenderingMode()==
"html5"?H.push(b):a.getRenderingMode()=="flash"&&a.getContainer().flowOnClick(b.toString())};this.hide=function(){if(a.getRenderingMode()=="html5"){if(!(i||c.style.display!="none"===false)){i=true;if(m())(new TWEEN.Tween(b)).to({size:0},400).easing(TWEEN.Easing.Cubic.EaseOut).onUpdate(v).onComplete(n).start();else{setTimeout(function(){if(b.showtext===true)l.style.opacity=0;g.hide(B)},100);if(e()){var d=e().style.webkitTransform;e().style.webkitTransform=d.replace(/translate\(.+?\)/,"translate(0px,0px)")}}for(d=
0;d<J.length;d++)J[d]()}}else a.getRenderingMode()=="flash"&&a.getContainer().flowHide()};this.show=function(){if(a.getRenderingMode()=="html5"){if(!(i||c.style.display!="none"===true)){i=true;r(true);if(m()){b.size=1;v();(new TWEEN.Tween(b)).to({size:K},400).easing(TWEEN.Easing.Cubic.EaseOut).onUpdate(v).onComplete(o).start()}else setTimeout(function(){c.style.opacity=1},100);for(var d=0;d<I.length;d++)I[d]()}}else a.getRenderingMode()=="flash"&&a.getContainer().flowShow()};this.onHide=function(b){a.getRenderingMode()==
"html5"?J.push(b):a.getRenderingMode()=="flash"&&a.getContainer().flowOnHide(b.toString())};this.onShow=function(b){a.getRenderingMode()=="html5"?I.push(b):a.getRenderingMode()=="flash"&&a.getContainer().flowOnShow(b.toString())};this.getDisplayElement=function(){return c};this.resize=function(i,e){if(a.getRenderingMode()=="html5"){if(i)d.width=i;if(e)d.height=e;var h=d.width,f=d.height;if(m()&&b.size>0){if(b.position=="left"||b.position=="right"){h=b.size;f=a.config.height;if(!C){C=true;a.resize(a.config.width-
h,a.config.height)}c.style[b.position]=-b.size+"px"}else if(b.position=="top"||b.position=="bottom"){h=a.config.width;f=b.size;if(!C){C=true;console.log(f)}if(b.position=="top")c.style.top=-f+"px";else if(b.position=="bottom")c.style.top=a.config.height-f+"px"}a.getContainer().style["margin"+(b.position.substr(0,1).toUpperCase()+b.position.substr(1))]=b.size+"px"}c.style.width=h+"px";c.style.height=f+"px";if(g){g.domElement.style.left=h*0.5+b.xposition+"px";g.domElement.style.top=f*0.5+b.yposition+
"px"}if(l)l.style.top=f-b.textoffset+"px"}else c.parentNode&&c.parentNode.removeChild(c)};D()};
Flow=function(a,b,c,p,f,e,m,A,y,z,v,B,n,o,q,w,u){function x(a){for(var b=0,c=a.currentTarget;c=c.previousSibling;)++b;b=r[b];if(a.offsetY<b.halfHeight){a.preventDefault();b.index!=k?h.to(b.index):h.clicked(b.index)}}function F(a){switch(a.keyCode){case 37:h.left();break;case 39:h.right();break;case 38:h.to(0);break;case 40:h.to(s-1);break;case 32:h.clicked(k)}}var h=this;this.GAP=f;this.ANGLE=e;this.DEPTH=-m;this.OFFSET=A+f;this.T_NEG_ANGLE="rotateY("+-this.ANGLE+"deg)";this.T_ANGLE="rotateY("+this.ANGLE+
"deg)";this.OPACITY=y;this.DURATION=w;this.showComplete=this.hideComplete=null;var r=[],s=b.length,D=0,d=0,k=0,g=[],l=[];this.domElement=document.createElement("div");this.domElement.setAttribute("id","flow_wrap");this.domElement.setAttribute("class","flow_wrap");f=document.createElement("div");f.setAttribute("id","flow_tray");f.setAttribute("class","flow_tray");this.domElement.appendChild(f);this.domElement.style.webkitPerspective=u;for(var u=new FlowDelegate(this,f),j=new TouchController(this,u,
f),t=null,e=0;e<b.length;e++){t=new FlowItem(h,e,b[e].image,b[e].duration,c,p,v,B,n,z,o,q);u.cells.push(t);f.appendChild(t.domElement);t.domElement.onmousedown=x;t.domElement.style.webkitTransitionDuration=w+"s";r[e]=t}t.domElement.firstChild.addEventListener("webkitTransitionEnd",function(a){a.stopPropagation();if(parseInt(t.domElement.firstChild.style.opacity,10)===0){h.domElement.style.opacity=0;typeof h.hideComplete=="function"&&h.hideComplete()}else parseInt(t.domElement.firstChild.style.opacity,
10)===1&&typeof h.showComplete=="function"&&h.showComplete()},true);this.hide=function(a){h.hideComplete=a;for(a=0;a<r.length;a++)r[a].domElement.firstChild.style.opacity=0};this.show=function(a){h.showComplete=a;h.domElement.style.opacity=1;for(a=0;a<r.length;a++)r[a].domElement.firstChild.style.opacity=1};this.itemComplete=function(a){d=d<a?a:d;++D;if(D==s){h.to(0);for(a=0;a<s;a++)r[a].setY(d)}};this.left=function(){k>0&&h.to(k-1)};this.right=function(){k<s-1&&h.to(k+1)};this.prev=function(){k>
0?h.to(k-1):h.to(s-1)};this.next=function(){k<s-1?h.to(k+1):h.to(0)};this.to=function(a){a>s-1?a=s-1:a<0&&(a=0);k=a;j.to(a)};this.focused=function(a){for(var b=0;b<g.length;b++)g[b](a)};this.clicked=function(a){for(var b=0;b<l.length;b++)l[b](a)};this.onFocus=function(a){g.push(a)};this.onClick=function(a){l.push(a)};this.destroy=function(){a.removeChild(h.domElement);a.removeEventListener("touchstart",j,true);window.removeEventListener("keydown",F,false)};a.addEventListener("touchstart",j,true);
window.addEventListener("keydown",F,false)};
FlowItem=function(a,b,c,p,f,e,m,A,y,z,v,B){var n=this,o,q;this.index=b;this.halfHeight=0;this.domElement=document.createElement("div");this.domElement.className="flow_cell";var w=this.domElement.style;w.backgroundColor=z;var u=document.createElement("canvas");n.domElement.appendChild(u);var x=document.createElement("img");x.addEventListener("load",function(){var b=x.width,c=x.height,r=0,s=0,p=0;if(v){var d=document.createElement("canvas");d.width=b;d.height=c;d=d.getContext("2d");d.drawImage(x,0,
0);for(var d=d.getImageData(0,0,b,c).data,k=0,g=0,l=0,j=0;j<c;j++){for(g=k=0;g<b;g++){l=(j*b+g)*4;k=k+(d[l]<<16|d[l+1]<<8|d[l+2])}if(k/b<460551)r++;else break}for(j=c-1;j>=0;j--){for(g=k=0;g<b;g++){l=(j*b+g)*4;k=k+(d[l]<<16|d[l+1]<<8|d[l+2])}if(k/b<460551)s++;else break}c=c-(r+s)}if(B){o=Math.round(f);q=Math.round(e);if(o/b<q/c){s=q/c;p=p+(b-o/s)*0.5}else{s=o/b;r=r+(c-q/s)*0.5}}else if(f>=e){o=Math.round(b/c*e);q=Math.round(e)}else{o=Math.round(f);q=Math.round(c/b*f)}n.halfHeight=q;w.top=-(q*0.5)+
"px";w.left=-(o*0.5)+"px";w.width=o+"px";w.height=q+"px";u.width=o;u.height=q*2;u.getContext("2d").drawImage(x,p,r,b-2*p,c-2*r,0,0,o,q);if(m>0){w.height=q*2+"px";n.reflect(u,o,q,m,A,y)}a.itemComplete(q)});x.src=c;this.setY=function(a){this.domElement.style.top=-(a*0.5-(a-q))+"px"}};
FlowItem.prototype.reflect=function(a,b,c,p,f,e){var m=a.getContext("2d");m.save();m.scale(1,-1);m.drawImage(a,0,-c*2-e);m.restore();m.globalCompositeOperation="destination-out";a=m.createLinearGradient(0,0,0,c);a.addColorStop(f/255,"rgba(255, 255, 255, 1.0)");a.addColorStop(0,"rgba(255, 255, 255, "+(1-p)+")");m.translate(0,c+e);m.fillStyle=a;m.fillRect(0,0,b,c)};TouchController=function(a,b,c){this.flow=a;this.delegate=b;this.elem=c;this.currentX=0};
TouchController.prototype.touchstart=function(a){a.stopImmediatePropagation();this.startX=a.touches[0].pageX-this.currentX;this.pageY=a.touches[0].pageY;this.touchMoved=false;window.addEventListener("touchmove",this,true);window.addEventListener("touchend",this,true);this.elem.style.webkitTransitionDuration="0s"};
TouchController.prototype.touchmove=function(a){a.stopImmediatePropagation();this.touchMoved=true;this.lastX=this.currentX;this.lastMoveTime=(new Date).getTime();this.currentX=a.touches[0].pageX-this.startX;this.delegate.update(this.currentX)};
TouchController.prototype.touchend=function(a){a.stopImmediatePropagation();window.removeEventListener("touchmove",this,true);window.removeEventListener("touchend",this,true);this.elem.style.webkitTransitionDuration=this.flow.DURATION+"s";if(this.touchMoved){var a=this.currentX-this.lastX,b=(new Date).getTime()-this.lastMoveTime+1;this.currentX=this.currentX+a*50/b;this.delegate.updateTouchEnd(this)}else this.delegate.click(a,this.pageY,this.currentX)};
TouchController.prototype.to=function(a){this.currentX=-a*this.delegate.flow.GAP;this.delegate.update(this.currentX)};TouchController.prototype.handleEvent=function(a){this[a.type](a);a.preventDefault()};FlowDelegate=function(a,b){this.flow=a;this.elem=b;this.cells=[];this.transforms=[];this.prevF=-1};FlowDelegate.prototype.updateTouchEnd=function(a){var b=this.getFocusedCell(a.currentX);a.currentX=-b*this.flow.GAP;this.update(a.currentX)};
FlowDelegate.prototype.getFocusedCell=function(a){a=-Math.round(a/this.flow.GAP);return Math.min(Math.max(a,0),this.cells.length-1)};FlowDelegate.prototype.getFocusedCellOne=function(a){a=-Math.round(a/this.flow.GAP);return Math.min(Math.max(a,-1),this.cells.length)};FlowDelegate.prototype.click=function(a,b,c){c=-Math.round(c/this.flow.GAP);c=this.cells[c];if(c.domElement==a.target.parentNode){a=this.findPos(c.domElement);b-a.y<c.halfHeight&&this.flow.clicked(c.index)}};
FlowDelegate.prototype.findPos=function(a){var b=0,c=0;if(a.offsetParent){do{b=b+a.offsetLeft;c=c+a.offsetTop}while(a=a.offsetParent);return{x:b,y:c}}};FlowDelegate.prototype.setStyleForCell=function(a,b,c){if(this.transforms[b]!=c){a.domElement.style.webkitTransform=c;this.transforms[b]=c}};
FlowDelegate.prototype.transformForCell=function(a,b){var c=b*this.flow.GAP;return a==b?"translate3d("+c+"px, 0, 0)":b>a?"translate3d("+(c+this.flow.OFFSET)+"px, 0, "+this.flow.DEPTH+"px) "+this.flow.T_NEG_ANGLE:"translate3d("+(c-this.flow.OFFSET)+"px, 0, "+this.flow.DEPTH+"px) "+this.flow.T_ANGLE};
FlowDelegate.prototype.update=function(a){this.elem.style.webkitTransform="translate3d("+a+"px, 0, 0)";var b=this.getFocusedCellOne(a);if(b!=this.prevF){this.flow.focused(b);for(var c=0;c<this.cells.length;c++)this.cells[c].domElement.style.zIndex=c<b?c:this.cells.length-c+b-1;this.prevF=b}for(c=0;c<this.cells.length;c++)this.setStyleForCell(this.cells[c],c,this.transformForCell(b,c,a))};jwplayer().registerPlugin("flow","6.0",main,"./flow-2.swf");
